version: "3"

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./static:/var/www/ship/static
      - ./distribution/nginx/${NGINX_CONFIG_NAME}:/etc/nginx/nginx.conf
      - ./distribution/nginx/include:/etc/nginx/include
      - ${SERVER_CERTIFICATE_DIRECTORY}:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"