# Playbook for Dropship Server Set-Up

---
- hosts: "{{ override_hosts | default('live') }}"

  vars_files:
    - ./vars/foundation.yml
    - ./vars/credentials.private.yml
  vars:
    ansible_user: "{{ server_user }}"

  tasks:
    # Services Start
    - import_tasks: ./custom/tasks/stop-services.yml

    # Services Set-Up
    - import_tasks: ./custom/tasks/set-up-services.yml

    # Services Start
    - import_tasks: ./custom/tasks/start-services.yml