# Playbook for Dropship Server Set-Up

---
- hosts: "{{ override_hosts | default('live') }}"

  vars_files:
    - ./vars/foundation.yml
    - ./vars/credentials.private.yml

  tasks:
    # Services Start
    - import_tasks: ./custom/tasks/stop-services.yml

    # Services Set-Up
    - import_tasks: ./custom/tasks/set-up-services.yml

    # Certificates
    - import_tasks: ./shared/tasks/set-up-certificates.yml
    - import_tasks: ./custom/tasks/set-up-certificate-crontab.yml

    # Services Start
    - import_tasks: ./custom/tasks/start-services.yml