# Playbook for System Set-Up

---
- hosts: "{{ override_hosts | default('live') }}"

  vars_files:
    - ./vars/foundation.yml

  tasks:
    - import_tasks: ./shared/tasks/set-up-ansible.yml
    - import_tasks: ./shared/tasks/set-up-docker.yml
    - import_tasks: ./shared/tasks/set-up-firewall.yml