# Playbook for System Set-Up

---
- hosts: all

  vars_files:
    - ./vars/foundation.yml

  vars:
    ansible_user: "{{ server_user }}"

  tasks:
    - import_tasks: ./shared/tasks/set-up-ansible.yml
    - import_tasks: ./shared/tasks/set-up-docker.yml
    - import_tasks: ./shared/tasks/set-up-firewall.yml