# Services Start

- name: "SERVER - Start server"
  docker_compose:
    project_name: "{{ app_label }}"
    project_src: "{{ app_root }}"
    restarted: yes
    build: yes
  environment:
    NGINX_CONFIG_NAME: "{{ nginx_config_name }}"
    SERVER_CERTIFICATE_DIRECTORY: "{{ server_certificate_directory }}"
    SERVER_CERTIFICATE_LOGS_DIRECTORY: "{{ server_certificate_logs_directory }}"
  become: yes
  tags:
    - services
    - services-start