# Environment

- name: "SERVER - Start procedure log"
  debug:
    msg: "Starting services in environment '{{ server_environment }}' Path lookup from '{{ lookup('env', 'PWD') }}'."
  tags:
    - services
    - services-start

- name: "SERVER - Set environment variables (for production)"
  set_fact:
    is_development_environment: no
    server_certificate_directory: "/etc/letsencrypt"
    nginx_config_name: "nginx.prod.conf"
  when: server_environment == 'production'
  tags:
    - services
    - services-start

- name: "SERVER - Set environment variables (for development)"
  set_fact:
    is_development_environment: yes
    server_certificate_directory: "/tmp/letsencrypt-dummy"
    nginx_config_name: "nginx.dev.conf"
  when: server_environment != 'production'
  tags:
    - services
    - services-start

# Services Start

- name: "SERVER - Start server"
  docker_compose:
    project_name: "freytag_drop"
    project_src: "."
    restarted: yes
  environment:
    NGINX_CONFIG_NAME: "{{ nginx_config_name }}"
    SERVER_CERTIFICATE_DIRECTORY: "{{ server_certificate_directory }}"
  tags:
    - services
    - services-start