# Services Start

- name: "SERVER - Start server"
  docker_compose:
    project_name: "{{ app_label }}"
    project_src: "{{ app_root }}"
    restarted: yes
  environment:
    COMPOSE_PROJECT_NAME: "freytag_drop"
    NGINX_CONFIG_NAME: "{{ nginx_config_name }}"
    SERVER_CERTIFICATE_LOG_ROOT: "{{ server_certificate_log_root }}"
    SERVER_CERTIFICATE_ROOT: "{{ server_certificate_root }}"
  become: yes
  tags:
    - services
    - services-start