# Playbook for Dropship Server Set-Up

---
- hosts: all
  vars_files:
    - ./vars/foundation.yml
    - ./vars/credentials.private.yml
  vars:
    server_environment: "production"
    ansible_user: "server"

  tasks:
    # Environment Set-Up
    - import_tasks: ./custom/tasks/set-up-environment.yml

    # Services Start
    - import_tasks: ./custom/tasks/stop-server.yml

    # Services Set-Up
    - import_tasks: ./custom/tasks/set-up-server.yml

    # Services Start
    - import_tasks: ./custom/tasks/start-server.yml