#################################################
# Playbook for Ship Server Set-Up
#################################################

---
- hosts: all
  vars_files:
    - ./vars/foundation.yml
    - ./vars/credentials.private.yml
  vars:
    server_environment: "production"
    ansible_user: "server"

  tasks:
    # System Set-Up
    - import_tasks: ./shared/tasks/set-up-ansible.yml
    - import_tasks: ./shared/tasks/set-up-docker.yml
    - import_tasks: ./shared/tasks/set-up-firewall.yml

    # Environment Set-Up
    - import_tasks: ./custom/tasks/set-up-environment.yml

    # Services Set-Up
    - import_tasks: ./custom/tasks/set-up-server.yml

    # Services Start
    - import_tasks: ./custom/tasks/start-server.yml