# Playbook for System Set-Up

---
- hosts: all

  vars:
    ansible_user: "root"
    server_user: "server"

  tasks:
    # System Set-Up
    - import_tasks: ./shared/tasks/set-up-ansible.yml
    - import_tasks: ./shared/tasks/set-up-docker.yml
    - import_tasks: ./shared/tasks/set-up-firewall.yml