# Variables

# "SERVER_NGINX_CONFIG_FILE"            NGINX configuration file name, mapped into the NGINX container. Example: "nginx.dev.conf"
# "SERVER_CERTIFICATE_DIR"              Path to the server's local certificate directory (not in container).
# "SERVER_CERTIFICATE_LOG_DIR"          Path to the server's local certificate log output directory (not in container).

version: "3.9"

services:
  proxy:
    build:
      context: ./server/docker
      dockerfile: nginx.dockerfile
    image: custom/nginx
    volumes:
      - ./static:/var/www/dropship/static
      - ./server/nginx/${SERVER_NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf
      - ./server/nginx/services:/etc/nginx/services
      - ./server/nginx/mixins:/etc/nginx/mixins
      - ${SERVER_CERTIFICATE_DIR}:/etc/letsencrypt
      - ${SERVER_CERTIFICATE_LOG_DIR}:/var/log/letsencrypt
    networks:
      - default
      - shared
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  default:
    name: dropship-default
  shared:
    name: dropship-shared