version: "3"

services:
  proxy:
    container_name: dropship_proxy
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./static:/var/www/ship/static
      - ./server/nginx/${SERVER_NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf
      - ./server/nginx/include:/etc/nginx/include
      - ${SERVER_CERTIFICATE_DIRECTORY}:/etc/letsencrypt
      - ${SERVER_CERTIFICATE_LOG_DIRECTORY}:/var/log/letsencrypt
    networks:
      - shared
    ports:
      - 80:80

networks:
  shared: