# Variables

# "SERVER_NGINX_CONFIG_FILE"            NGINX configuration file name, mapped into the NGINX container. Example: "nginx.dev.conf"
# "SERVER_CERTIFICATE_DIRECTORY"        Path to the server's local certificate directory (not in container).
# "SERVER_CERTIFICATE_LOG_DIRECTORY"    Path to the server's local certificate log output directory (not in container).

version: "3.9"

services:
  proxy:
    container_name: dropship_proxy
    build:
      context: ./server/docker
      dockerfile: nginx.dockerfile
    image: custom-nginx
    volumes:
      - ./static:/var/www/ship/static
      - ./server/nginx/${SERVER_NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf
      - ./server/nginx/include:/etc/nginx/include
      - ${SERVER_CERTIFICATE_DIRECTORY}:/etc/letsencrypt
      - ${SERVER_CERTIFICATE_LOG_DIRECTORY}:/var/log/letsencrypt
    networks:
      - shared
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  shared: