---
host_root: "{{ playbook_dir }}/../.."
host_root_escaped: "{{ host_root | replace(\" \", \"\\ \") }}"

# Server
ansible_user: "server"
server_user: "server"
server_certificate_directory: "/etc/letsencrypt"
server_certificate_log_directory: "/var/log/letsencrypt"

server_domains:
  [
    { name: "augustfreytag.com", domains: "augustfreytag.com,www.augustfreytag.com" },
    { name: "cockpit.augustfreytag.com", domains: "cockpit.augustfreytag.com" },
    { name: "drop.augustfreytag.com", domains: "drop.augustfreytag.com" },
    { name: "analytics.augustfreytag.com", domains: "analytics.augustfreytag.com" },
  ]

# App
app_repository: "gitlab.com/apricum/freytag-dropship.git"
app_version: "master"

app_root: "/var/www/dropship"
app_server_directory: "{{ app_root }}/server"

docker_directory: "{{ app_server_directory }}/docker"
proxy_directory: "{{ app_server_directory }}/nginx"

# Proxy
proxy_config_name: "nginx.live.conf"
