# Services Start

- name: "SERVER - Start application services"
  shell:
    cmd: "docker-compose --file {{ docker_directory }}/docker-compose.yml --project-name dropship --project-directory {{ app_root }} --env-file {{ docker_directory }}/env/parameters.production.env up -d"
  become: yes
  tags:
    - services
    - services-start